### PR TITLE
36 Easily Configurable ID Prefix 

### LINKED ISSUE #36: Easily confligurable id prefix
**As a** cheminformatician using the system to manage chemical structure data that is not part of EPA production DSSTox database
**I want** to easily control the prefix that is used when minting new compound ids as part of the deployment process
**So that** when I deploy a private version, I can mint ids that are clearly different from those in the production system

**Acceptance Criteria:**
Documentation indicating the way to control the prefix (e.g. the "DTX" in DTXCID).   When following that documentation, I can change the "DTX" prefix to any string I want.

**Test:**

### PR DESCRIPTION
**Pull request by AScaduto**
closes #36

We now have the ability to specify a Custom CID prefix via a custom template env field

Documentation added to the Wiki as well:
https://github.com/Chemical-Curation/chemcurator_django/wiki/Configuration#compound_prefix-TOC

### CODE REVIEW

**Comment by AScaduto** [comment]
Based on the logic written in chemreg\compound\settings.py

**
image
**

I needed to include a default in config\settings.py 
"COMPOUND = {"PREFIX": env("COMPOUND_PREFIX", default="DTX")}"

Without this default, if the new COMPOUND_PREFIX environment variable is commented out or left blank, a blank string will be concatenated onto the CID rather than DTX. 

If you happen to think of a better way of handling this let me know
https://django-environ.readthedocs.io/en/latest/

**Comment by AScaduto** [comment]
@mwfrost I went ahead and added tests that validate the prefix for both defined and ill defined compounds; Let me know what you think

**Comment by debboutr** [comment]
hey, should we include the default in the `template.env`? If a user were to copy that file and not edit the prefix, there would be none `""` and the fact that it's declared would override the default in `config.settings`

`COMPOUND_PREFIX=DTX`

**Comment by mwfrost** [comment]
> hey, should we include the default in the `template.env`? If a user were to copy that file and not edit the prefix, there would be none `""` and the fact that it's declared would override the default in `config.settings`
> 
> `COMPOUND_PREFIX=DTX`

Yes, absolutely. I am doing that on my working copy.

**Pull request merged**
