### PR TITLE
19 created_by / updated by

### LINKED ISSUE #19: created by/updated by
As the ChemReg product owner
I want to be able to store created at, updated at, created by updated by as fields for every data model in the application
so that I can track who is doing what and when in my application

Acceptance Criteria
- created at, updated at, created by, updated by fields exist in every data model
- when object is created, created and updated at fields would be populated with same date/time, and created by/updated by fields would be populated with same user

### PR DESCRIPTION
**Pull request by mcovalt**
Closes #19 

This PR makes all models have a `created_by` and `updated_by` field. It uses [`django-crum`](https://github.com/ninemoreminutes/django-crum) to find the user making the request.

### CODE REVIEW

**Comment by debboutr** [comment]
This all looks fine, but I seem to have run into a problem migrating backwards/forwards after I initially migrated what's on this branch. I get an error at the `compound` migration 0005.

`django.db.utils.ProgrammingError: column compound_querystructuretype.created_by_id does not exist`

this wouldn't too big of problem if it only got thrown when going backwards, but with an empty schema I can't migrate forwards, so, if someone else can check to see that this problem exists and I'm not crazy, we can figure it out. I've already tried wiping every migrations and just making a new one and that works fine so that'll be easy enough to implement.

**Comment by mcovalt** [comment]
Thanks for noticing this.

This is due to `chemreg.models.get_illdefined_qst` being called during the migration. The new model definition includes fields not present in the database in migration `0005_illdefinedcompoundquerystructuretype`.

The migration to add these fields was moved up in the chain as a fix.

**Comment by debboutr** [comment]
if I go to the sprint branch and completely reset the DB, then go to this feature branch and try to migrate I will first get en error from `migrate`:

`django.db.migrations.exceptions.InconsistentMigrationHistory: Migration compound.0005_illdefinedcompoundquerystructuretype is applied before its dependency compound.0005_createdby_updated_by on database 'default'.`

 I tried to run `migrate users` to see if that would help, but I get the same error. Can't we just slash these migrations and start back at 0001? If we won't be able to migrate backwards anyway, there is no need to keep them individualized.

**Comment by mcovalt** [comment]
Alright. Things should be good now. Migrations have been collapsed and the issue with the default foreign key has been resolved by installing that fixture via a data-migration.

You'll need to nuke and reload the database. For `pytest` this is easy: `pytest --create-db`.

**Pull request merged**
